<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LBN8TGD" ignored="0" name="RetryMulitple(failed)" tests="10" failures="1" timestamp="29 Mar 2019 11:53:43 GMT" time="0.037" errors="0">
  <testcase name="run" time="0.008" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.001" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng.TestRetry1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testng.TestRetry1.run(TestRetry1.java:11)
at testng.MultRetry.main(MultRetry.java:15)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- run -->
</testsuite> <!-- RetryMulitple(failed) -->
